name: publish to nuget
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      # slnファイルの存在するフォルダの相対パス
      SolutionPath: src

      # nupkgのビルド結果があるbinのパス
      # プロジェクトが複数ある場合はすべて登録すること
      NugetPackagePath: src/<projectName>/bin/Release

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Add Source
        run: 
          dotnet nuget add source "https://nuget.pkg.github.com/miles-team/index.json" -n github -u ${{ secrets.NUGET_GITHUB_USER }} -p ${{ secrets.NUGET_GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore ${SolutionPath}

      - name: Build
        run: dotnet build ${SolutionPath} --no-restore --configuration release

      - name: Pack
        run: dotnet pack ${SolutionPath}  --configuration release

      - name: Push
        run: |
          cd ${NugetPackagePath}
          dotnet nuget push *.nupkg --source github --api-key ${{ secrets.NUGET_GITHUB_TOKEN }} --skip-duplicate
